# -*- coding: utf-8 -*-
"""
Created on Fri Jun 11 18:01:40 2021

@author: Wenna
"""

# create a dictionary of slangs/typos
manual_typos_dict = {"anddd" : "and",
                     "basiaclly" : "basically",
                     "bleeeddd" : "bleed",
                     "dodgecoin" : "dogecoin",
                     "dogecoind" : "dogecoin",
                     "dogcoin" : "dogecoin",
                     "dogdecoins" : "dogecoin",
                     "dogecoing" : "dogecoin",
                     "doejehcoin" : "dogecoin",
                     "foldddd" : "fold",
                     "goo" : "go",
                     "gooo" : "go",
                     "goooo" : "go",
                     "gooooo" : "go",
                     "goooooo" : "go",
                     "gooooooo" : "go",
                     "goooooooing" : "going",
                     "goooooooood" : "good",
                     "goooooooooooiooo" : "go",
                     "gooooooooooooo" : "go",
                     "goooooooooooooooo" : "go",
                     "hodl" : "hold",
                     "holdddd" : "hold",
                     "hooooold" : "hold",
                     "holdddddd" : "hold",
                     "holddddd" : "hold",
                     "hodddddddlllllllll" : "hold",
                     "holdddddddddddd" : "hold",
                     "holddd" : "hold",
                     "hooooooold" : "hold",
                     "hodddllll" : "hold",
                     "holddddddddd" : "hold",
                     "holdddddddd" : "hold",
                     "hoooollldddd" : "hold",
                     "hooooooooooooooooooooddddddllll" : "hold",
                     "hooooooolllllldddd" : "hold",
                     "hoooooooddddllllll" : "hold",
                     "hoooooollllldddd" : "hold",
                     "hoooolllddd" : "hold",
                     "holllddddddddd" : "hold",
                     "hollllddddd" : "hold",
                     "hooolllldddd" : "hold",
                     "hooolllddddddddd" : "hold",
                     "hooolllddd" : "hold",
                     "hoolllddd" : "hold",
                     "holdddddddddddddddd" : "hold",
                     "holddddddddddddd" : "hold",
                     "hodddllllllll" : "hold",
                     "hodddlll" : "hold",
                     "hoddddllll" : "hold",
                     "holdddddddddd" : "hold",
                     "hhooooollllllllddddd" : "hold",
                     "instituitions" : "institutions",
                     "leggo": "let's go",
                     "legggo": "let's go",
                     "letsgo": "let's go",
                     "lezzgo": "let's go",
                     "leeeettttsssss" : "let's",
                     "lmaooo" : "lmao",
                     "lmaoooo" : "lmao",
                     "moooooon" : "moon",
                     "mooon" : "moon",
                     "moooon" : "moon",
                     "mooooon" : "moon",
                     "mooooooon" : "moon",
                     "mooonnn" : "moon",
                     "moooooooon" : "moon",
                     "moonn" : "moon",
                     "mooooooooon" : "moon",
                     "mooonnnn" : "moon",
                     "moonnnn" : "moon",
                     "mooooonnnn" : "moon",
                     "moooonnnnnn" : "moon",
                     "moooonnnn" : "moon",
                     "moooonnn" : "moon",
                     "mooooooonnn" : "moon",
                     "moooooonnnn" : "moon",
                     "moooooooonnn" : "moon",
                     "mooooooooonnnnn" : "moon",
                     "moooooooooooooooooooooooon" : "moon",
                     "mooooooooooooonnnnnnnnn" : "moon",
                     "mooooooooooooon" : "moon",
                     "mmmmmmmmmoon" : "moon",
                     "ogecoin" : "dogecoin",
                     "preeeetttyyy" : "pretty",
                     "scaredddd" : "scared",
                     "spreadig" : "spreading",
                     "sucess" : "success",
                     "sucessfull" : "successful",
                     "syckkkkk": "sick",
                     "unterstand": "understand",
                     "yassssss": "yes"}